import PassantCodeQ13.WeightTen.Reachability
import PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre5

/-!
# Right-hand option bridge for an isolated weight-ten fibre

This file is generated by `generate_weight_ten_reachability.py`.  Kernel reduction checks that
the compact syndrome-increment lists for distinguished passant fibre 5 agree with the
normalized conic incidence columns used by the formal Cartesian domain.
-/

namespace PassantCodeQ13.WeightTen.IsolatedReachability.Fibre5.RightOptions

open PassantCodeQ13.WeightTen

set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

/-- The generated increment lists equal the executable normalized-incidence option lists. -/
theorem checked : isolatedRightOptions 5 = PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre5.rightOptions := by
  unfold PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre5.rightOptions
  unfold isolatedRightOptions remainingFibres columnOptions fibres linesThroughBase columnSyndrome
    incidentAt internalAt passantAt xorColumns
  unfold RelativeConicArcs.PassantCodeQ13.internalCoordinateList
    RelativeConicArcs.PassantCodeQ13.passantCoordinateList
    RelativeConicArcs.PassantCodeQ13.projectiveTripleList
    RelativeConicArcs.PassantCodeQ13.fieldElements
    RelativeConicArcs.PassantCodeQ13.pointDiscriminant
    RelativeConicArcs.PassantCodeQ13.lineDiscriminant
    RelativeConicArcs.PassantCodeQ13.isNonzeroSquare
    RelativeConicArcs.PassantCodeQ13.affineTriple
    RelativeConicArcs.PassantCodeQ13.infiniteTriple
    RelativeConicArcs.PassantCodeQ13.verticalTriple
  decide +kernel

end PassantCodeQ13.WeightTen.IsolatedReachability.Fibre5.RightOptions
