import PassantCodeQ13.WeightTen.Reachability
import PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre1

/-!
# Terminal disjointness for an isolated weight-ten fibre

This file is generated by `generate_weight_ten_reachability.py`.  Kernel reduction checks that
the two terminal reachable-state lists for distinguished passant fibre 1 are disjoint.
-/

namespace PassantCodeQ13.WeightTen.IsolatedReachability.Fibre1.TerminalDisjoint.FirstThird

open PassantCodeQ13.WeightTen.Reachability
open PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre1

set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

/-- This Cartesian-enumeration third is disjoint from the terminal right-hand states. -/
theorem checked :
    disjointCheck PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre1.leftTerminalFirstThird PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre1.rightOrdinaryC = true := by
  unfold PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre1.leftTerminalFirstThird PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre1.rightOrdinaryC
  unfold disjointCheck
  decide +kernel

end PassantCodeQ13.WeightTen.IsolatedReachability.Fibre1.TerminalDisjoint.FirstThird
