import PassantCodeQ13.WeightTen.Reachability
import PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre2

/-!
# One right-hand transition for an isolated weight-ten fibre

This file is generated by `generate_weight_ten_reachability.py`.  Kernel reduction checks the
canonical successor list for one mathematical choice in distinguished passant fibre 2.
The profile aggregator combines the independently compiled transition theorems.
-/

namespace PassantCodeQ13.WeightTen.IsolatedReachability.Fibre2.RightOrdinaryA

open PassantCodeQ13.WeightTen
open PassantCodeQ13.WeightTen.Reachability
open PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre2

set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

/-- This generated layer is exactly the canonical XOR-successor list for its Cartesian choice. -/
theorem transition_checked :
    transitionCheck PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre2.rightDistinguishedTriple (PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre2.rightOptions.getD 2 []) PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre2.rightOrdinaryA = true := by
  unfold PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre2.rightDistinguishedTriple PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre2.rightOrdinaryA PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre2.rightOptions
  unfold transitionCheck transitionSuccessors
  decide +kernel

end PassantCodeQ13.WeightTen.IsolatedReachability.Fibre2.RightOrdinaryA
