#!/usr/bin/env python3
"""Generate the exact binary transport data for the semantic rank theorem."""

from __future__ import annotations

import argparse
from pathlib import Path


Q = 13
OUTPUT = Path(__file__).parent / "PassantCodeQ13" / "RankTransportData.lean"


def projective_triples() -> list[tuple[int, int, int]]:
    return (
        [(1, y, z) for y in range(Q) for z in range(Q)]
        + [(0, 1, z) for z in range(Q)]
        + [(0, 0, 1)]
    )


def incidence_columns() -> list[int]:
    squares = {value * value % Q for value in range(1, Q)}
    triples = projective_triples()
    internal = [
        point for point in triples
        if (point[1] * point[1] - point[0] * point[2]) % Q not in squares | {0}
    ]
    passants = [
        line for line in triples
        if (line[1] * line[1] - 4 * line[0] * line[2]) % Q not in squares | {0}
    ]
    assert len(internal) == len(passants) == 78
    return [
        sum(
            1 << row
            for row, line in enumerate(passants)
            if sum(a * b for a, b in zip(line, point)) % Q == 0
        )
        for point in internal
    ]


def expansion_masks(columns: list[int]) -> list[int]:
    pivots: dict[int, tuple[int, int]] = {}
    masks: list[int] = []
    basis_size = 0
    for column in columns:
        value = column
        combination = 0
        while value:
            pivot = value.bit_length() - 1
            if pivot in pivots:
                pivot_value, pivot_mask = pivots[pivot]
                value ^= pivot_value
                combination ^= pivot_mask
            else:
                assert basis_size < 42
                unit = 1 << basis_size
                pivots[pivot] = (value, combination ^ unit)
                masks.append(unit)
                basis_size += 1
                break
        else:
            masks.append(combination)
    assert basis_size == 42
    assert masks[:42] == [1 << index for index in range(42)]
    return masks


def recovery_masks(columns: list[int]) -> list[int]:
    rows = [
        sum(((columns[column] >> row) & 1) << column for column in range(42))
        for row in range(42)
    ]
    augmented = [row | (1 << (42 + index)) for index, row in enumerate(rows)]
    for column in range(42):
        pivot = next(row for row in range(column, 42) if augmented[row] >> column & 1)
        augmented[column], augmented[pivot] = augmented[pivot], augmented[column]
        for row in range(42):
            if row != column and augmented[row] >> column & 1:
                augmented[row] ^= augmented[column]
    assert [row & ((1 << 42) - 1) for row in augmented] == [1 << i for i in range(42)]
    return [row >> 42 for row in augmented]


def lean_list(values: list[int]) -> str:
    lines = []
    for start in range(0, len(values), 5):
        lines.append("  " + ", ".join(map(str, values[start : start + 5])))
    return ",\n".join(lines)


def render() -> str:
    columns = incidence_columns()
    recovery = recovery_masks(columns)
    expansion = expansion_masks(columns)
    return f'''/-!
# Generated binary rank-transport data

This file is generated by `generate_rank_transport.py`.  The first list gives 42 linear
functionals left inverse to the first 42 incidence columns.  The second expresses all 78 columns
in that basis.  Lean checks both meanings against the normalized conic incidence relation.
-/

namespace PassantCodeQ13.RankTransportData

/-- Recovery masks for the first 42 incidence columns. -/
def recoveryMask (index : Fin 42) : Nat := [
{lean_list(recovery)}].get index

/-- Expansion masks for all 78 incidence columns. -/
def columnExpansionMask (index : Fin 78) : Nat := [
{lean_list(expansion)}].get index

end PassantCodeQ13.RankTransportData
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit(f"stale generated file: {OUTPUT}")
        print("q=13 semantic rank transport data: PASS")
    else:
        OUTPUT.write_text(expected)


if __name__ == "__main__":
    main()
