import PassantCodeQ13.Gates.Main

/-!
# Axiom audit for the finite q=13 passant-code leaves

The commands print the actual axiom dependencies of every aggregate native terminal under the
pinned Lean toolchain.  Native evaluation is expected to expose declaration-local axioms.
-/

#print axioms PassantCodeQ13.WeightTen.local_partition
#print axioms PassantCodeQ13.WeightTen.all_isolated_profiles_disjoint
#print axioms PassantCodeQ13.WeightTen.all_cycle_profiles_disjoint
#print axioms PassantCodeQ13.WeightTen.cycle_pair_partition
#print axioms PassantCodeQ13.Rank.incidenceRows_rank
#print axioms PassantCodeQ13.SemanticTransports.recoverCoefficient_basisColumn
#print axioms PassantCodeQ13.SemanticTransports.incidenceColumn_expansion
#print axioms PassantCodeQ13.SemanticTransports.incidenceMap_has_rank_fortyTwo
#print axioms PassantCodeQ13.Gates.Main.incidenceRankAndCodeDimension
#print axioms PassantCodeQ13.AssociationAlgebra.relation_matrix_ranks
#print axioms PassantCodeQ13.AssociationAlgebra.rhoZero_square
#print axioms PassantCodeQ13.AssociationAlgebra.rankThirtySix_squaring_cycle
#print axioms PassantCodeQ13.AssociationTransport.booleanParityProduct_linearize
#print axioms PassantCodeQ13.AssociationTransport.rhoZero_square_entry_certificate
#print axioms PassantCodeQ13.AssociationTransport.rhoNine_square_entry_certificate
#print axioms PassantCodeQ13.AssociationTransport.rhoTen_square_entry_certificate
#print axioms PassantCodeQ13.AssociationTransport.rhoTwelve_square_entry_certificate
#print axioms PassantCodeQ13.AssociationTransport.relation_matrix_identities
#print axioms PassantCodeQ13.AssociationTransport.orbitS4_entry_certificate
#print axioms PassantCodeQ13.AssociationTransport.orbitDihedralA_entry_certificate
#print axioms PassantCodeQ13.AssociationTransport.orbitDihedralB_entry_certificate
#print axioms PassantCodeQ13.AssociationTransport.orbitDihedralC_entry_certificate
#print axioms PassantCodeQ13.AssociationTransport.every_minimum_orbit_spans_rhoZero_kernel
#print axioms PassantCodeQ13.MinimumWords.orbitS4_size_and_kernel
#print axioms PassantCodeQ13.MinimumWords.orbitS4_rank
#print axioms PassantCodeQ13.MinimumWords.orbitDihedralA_certificate
#print axioms PassantCodeQ13.MinimumWords.orbitDihedralB_certificate
#print axioms PassantCodeQ13.MinimumWords.orbitDihedralC_certificate
#print axioms PassantCodeQ13.MinimumWords.dihedral_orbits_pairwise_disjoint
#print axioms PassantCodeQ13.MinimumWords.minimumSupportCodes_length
#print axioms PassantCodeQ13.MinimumWords.fixedPoint_weightTwelve_exhaustion
#print axioms PassantCodeQ13.MinimumWords.fixedPoint_slices_are_stabilizer_orbits
#print axioms PassantCodeQ13.MinimumWords.pair_concurrence_recovers_passant_join
#print axioms PassantCodeQ13.MinimumWords.geometric_rows_have_zero_triple_signatures
#print axioms PassantCodeQ13.MinimumWords.RowUniqueness.row_extension_residue_zero
#print axioms PassantCodeQ13.MinimumWords.RowUniqueness.row_extension_residue_one
#print axioms PassantCodeQ13.MinimumWords.RowUniqueness.row_extension_residue_two
#print axioms PassantCodeQ13.MinimumWords.RowUniqueness.row_extension_residue_three
#print axioms PassantCodeQ13.MinimumWords.RowUniqueness.row_extension_residue_four
#print axioms PassantCodeQ13.MinimumWords.RowUniqueness.row_extension_residue_five
#print axioms PassantCodeQ13.MinimumWords.RowUniqueness.row_extension_residue_six
#print axioms PassantCodeQ13.MinimumWords.RowUniqueness.decodedSupport_injOn
#print axioms PassantCodeQ13.MinimumWords.RowUniqueness.indexedPassantJoin_eq_true_iff
#print axioms PassantCodeQ13.MinimumWords.RowUniqueness.indexedTripleConcurrence_eq_semantic
#print axioms PassantCodeQ13.MinimumWords.RowUniqueness.row_extension_check_all_indices
#print axioms PassantCodeQ13.MinimumWords.RowUniqueness.geometric_rows_have_zero_triple_concurrence
#print axioms PassantCodeQ13.MinimumWords.RowUniqueness.reconstructionCandidateCheck_eq_true_iff
#print axioms PassantCodeQ13.MinimumWords.RowUniqueness.admissible_seven_set_is_geometric_row
#print axioms PassantCodeQ13.MinimumWords.RowUniqueness.reconstructed_rows_eq_geometric_passant_rows
#print axioms PassantCodeQ13.Automorphisms.projectiveMatrices_length
#print axioms PassantCodeQ13.Automorphisms.anchorTriplePattern
#print axioms PassantCodeQ13.Automorphisms.matrixAction_bijective
#print axioms PassantCodeQ13.Automorphisms.matrixAction_preservesRho
#print axioms PassantCodeQ13.Automorphisms.projectiveAnchorTriples_eq_patterned
#print axioms PassantCodeQ13.Automorphisms.firstThreeSignature_eq_iff
#print axioms PassantCodeQ13.Automorphisms.anchorSignature_injective
#print axioms PassantCodeQ13.Automorphisms.preservesRho_iff_projective
#print axioms PassantCodeQ13.Gates.Main.weightTenCertificate
#print axioms PassantCodeQ13.Gates.Main.arbitraryWeightTenProfileTransport
#print axioms PassantCodeQ13.Gates.Main.minimumOrbitCertificate
#print axioms PassantCodeQ13.Gates.Main.fixedPointWeightTwelveExhaustion
#print axioms PassantCodeQ13.Gates.Main.fixedPointSlicesAreStabilizerOrbits
#print axioms PassantCodeQ13.Gates.Main.recoveredRowFamilyIsUnique
#print axioms PassantCodeQ13.Gates.Main.minimumOrbitsSpanRhoZeroKernel
#print axioms PassantCodeQ13.Gates.Main.ellipticSchemeAutomorphismsAreProjective
#print axioms RelativeConicArcs.PassantCodeQ13.cliqueSize_le_five_of_theta_inequality
#print axioms RelativeConicArcs.PassantCodeQ13.weightTenMoment_two_shapes
#print axioms RelativeConicArcs.PassantCodeQ13.pencilConic_doubleRoot_discriminant
#print axioms RelativeConicArcs.PassantCodeQ13.hiddenCubic_of_quartic
#print axioms PassantCodeQ13.StructuralUpgrade.unaryDegree_fiftySix
#print axioms PassantCodeQ13.StructuralUpgrade.pairColorEight_recovers_polarRows
#print axioms PassantCodeQ13.StructuralUpgrade.fusedColorSix_splits
#print axioms PassantCodeQ13.StructuralUpgrade.toricSupport_cards
#print axioms PassantCodeQ13.StructuralUpgrade.toricSupport_even_passants
#print axioms PassantCodeQ13.StructuralUpgrade.hiddenField_cubic_on_image
#print axioms PassantCodeQ13.StructuralUpgrade.determinantConic_card
#print axioms PassantCodeQ13.StructuralUpgrade.uniqueLine_through_two_points
#print axioms PassantCodeQ13.StructuralUpgrade.uniquePoint_on_two_lines
#print axioms PassantCodeQ13.Gates.Main.pairOnlyReconstruction
#print axioms PassantCodeQ13.Gates.Main.toricMinimumSupports
#print axioms PassantCodeQ13.Gates.Main.hiddenFieldCubicOnImage
#print axioms PassantCodeQ13.Gates.Main.ambientPlaneIncidence
