import PassantCodeQ13.WeightTen.Reachability
import PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre3

/-!
# One right-hand transition for an isolated weight-ten fibre

This file is generated by `generate_weight_ten_reachability.py`.  Kernel reduction checks the
canonical successor list for one mathematical choice in distinguished passant fibre 3.
The profile aggregator combines the independently compiled transition theorems.
-/

namespace PassantCodeQ13.WeightTen.IsolatedReachability.Fibre3.RightOrdinaryC

open PassantCodeQ13.WeightTen
open PassantCodeQ13.WeightTen.Reachability
open PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre3

set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

/-- This generated layer is exactly the canonical XOR-successor list for its Cartesian choice. -/
theorem transition_checked :
    transitionCheck PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre3.rightOrdinaryB (PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre3.rightOptions.getD 4 []) PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre3.rightOrdinaryC = true := by
  unfold PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre3.rightOrdinaryB PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre3.rightOrdinaryC PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre3.rightOptions
  unfold transitionCheck transitionSuccessors
  decide +kernel

end PassantCodeQ13.WeightTen.IsolatedReachability.Fibre3.RightOrdinaryC
