import PassantCodeQ13.WeightTen.Reachability
import PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre1

/-!
# Left-hand option bridge for an isolated weight-ten fibre

This file is generated by `generate_weight_ten_reachability.py`.  Kernel reduction checks that
the compact syndrome-increment lists for distinguished passant fibre 1 agree with the
normalized conic incidence columns used by the formal Cartesian domain.
-/

namespace PassantCodeQ13.WeightTen.IsolatedReachability.Fibre1.LeftOptions

open PassantCodeQ13.WeightTen

set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

/-- The generated increment lists equal the executable normalized-incidence option lists. -/
theorem checked : isolatedLeftOptions 1 = PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre1.leftOptions := by
  unfold PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre1.leftOptions
  unfold isolatedLeftOptions remainingFibres columnOptions fibres linesThroughBase columnSyndrome
    incidentAt internalAt passantAt
  unfold RelativeConicArcs.PassantCodeQ13.internalCoordinateList
    RelativeConicArcs.PassantCodeQ13.passantCoordinateList
    RelativeConicArcs.PassantCodeQ13.projectiveTripleList
    RelativeConicArcs.PassantCodeQ13.fieldElements
    RelativeConicArcs.PassantCodeQ13.pointDiscriminant
    RelativeConicArcs.PassantCodeQ13.lineDiscriminant
    RelativeConicArcs.PassantCodeQ13.isNonzeroSquare
    RelativeConicArcs.PassantCodeQ13.affineTriple
    RelativeConicArcs.PassantCodeQ13.infiniteTriple
    RelativeConicArcs.PassantCodeQ13.verticalTriple
  decide +kernel

end PassantCodeQ13.WeightTen.IsolatedReachability.Fibre1.LeftOptions
