import PassantCodeQ13.WeightTen.Reachability
import PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre1

/-!
# One right-hand transition for an isolated weight-ten fibre

This file is generated by `generate_weight_ten_reachability.py`.  Kernel reduction checks the
canonical successor list for one mathematical choice in distinguished passant fibre 1.
The profile aggregator combines the independently compiled transition theorems.
-/

namespace PassantCodeQ13.WeightTen.IsolatedReachability.Fibre1.RightOrdinaryB

open PassantCodeQ13.WeightTen
open PassantCodeQ13.WeightTen.Reachability
open PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre1

set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

/-- This generated layer is exactly the canonical XOR-successor list for its Cartesian choice. -/
theorem transition_checked :
    transitionCheck PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre1.rightOrdinaryA (PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre1.rightOptions.getD 3 []) PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre1.rightOrdinaryB = true := by
  unfold PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre1.rightOrdinaryA PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre1.rightOrdinaryB PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre1.rightOptions
  unfold transitionCheck transitionSuccessors
  decide +kernel

end PassantCodeQ13.WeightTen.IsolatedReachability.Fibre1.RightOrdinaryB
