import PassantCodeQ13.WeightTen.Reachability
import PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre3

/-!
# Terminal disjointness for an isolated weight-ten fibre

This file is generated by `generate_weight_ten_reachability.py`.  Kernel reduction checks that
the two terminal reachable-state lists for distinguished passant fibre 3 are disjoint.
-/

namespace PassantCodeQ13.WeightTen.IsolatedReachability.Fibre3.TerminalDisjoint.MiddleThird

open PassantCodeQ13.WeightTen.Reachability
open PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre3

set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

/-- This Cartesian-enumeration third is disjoint from the terminal right-hand states. -/
theorem checked :
    disjointCheck PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre3.leftTerminalMiddleThird PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre3.rightOrdinaryC = true := by
  unfold PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre3.leftTerminalMiddleThird PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre3.rightOrdinaryC
  unfold disjointCheck
  decide +kernel

end PassantCodeQ13.WeightTen.IsolatedReachability.Fibre3.TerminalDisjoint.MiddleThird
