import PassantCodeQ13.WeightTen.Reachability
import PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre0

/-!
# Terminal disjointness for an isolated weight-ten fibre

This file is generated by `generate_weight_ten_reachability.py`.  Kernel reduction checks that
the two terminal reachable-state lists for distinguished passant fibre 0 are disjoint.
-/

namespace PassantCodeQ13.WeightTen.IsolatedReachability.Fibre0.TerminalDisjoint.FirstThird

open PassantCodeQ13.WeightTen.Reachability
open PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre0

set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

/-- This Cartesian-enumeration third is disjoint from the terminal right-hand states. -/
theorem checked :
    disjointCheck PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre0.leftTerminalFirstThird PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre0.rightOrdinaryC = true := by
  unfold PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre0.leftTerminalFirstThird PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre0.rightOrdinaryC
  unfold disjointCheck
  decide +kernel

end PassantCodeQ13.WeightTen.IsolatedReachability.Fibre0.TerminalDisjoint.FirstThird
