import PassantCodeQ13.WeightTen.Reachability
import PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre4

/-!
# One left-hand transition for an isolated weight-ten fibre

This file is generated by `generate_weight_ten_reachability.py`.  Kernel reduction checks the
canonical successor list for one mathematical choice in distinguished passant fibre 4.
The profile aggregator combines the independently compiled transition theorems.
-/

namespace PassantCodeQ13.WeightTen.IsolatedReachability.Fibre4.LeftOrdinaryA

open PassantCodeQ13.WeightTen
open PassantCodeQ13.WeightTen.Reachability
open PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre4

set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

/-- This generated layer is exactly the canonical XOR-successor list for its Cartesian choice. -/
theorem transition_checked :
    transitionCheck [0] (PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre4.leftOptions.getD 0 []) PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre4.leftOrdinaryA = true := by
  unfold PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre4.leftOrdinaryA PassantCodeQ13.WeightTen.ReachabilityData.IsolatedFibre4.leftOptions
  unfold transitionCheck transitionSuccessors
  decide +kernel

end PassantCodeQ13.WeightTen.IsolatedReachability.Fibre4.LeftOrdinaryA
